config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  # POST "/sales?method=calcCost"
  post "sales/calcCost" => "sales#calcCost"

  resources :articles, :recipes, :recipedetails, :purchases
  resources :sales do
    resources :sale_packages
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :purchases

  validates :name, presence: true
  validates :category, presence: true
  validates :unit, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :article
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :sales
end

app/models/recipe_detail.rb
class RecipeDetail < ApplicationRecord
  belongs_to :article
  belongs_to :recipe
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :recipe
  has_many :sale_packages
end

app/models/sale_package.rb
class SalePackage < ApplicationRecord
  belongs_to :sale
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @lastPrice = Purchase.where("article_id = ?", @article.id).order("created_at DESC").first
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end
  #
  # def getLastPrice
  #   @article = Article.find(params[:id])
  #   @lastPrice = Purchase.find_by_article_id(@article.id).order("created_at DESC").limit(1)
  # end

  private
  def article_params
    params.require(:article).permit(:name, :category, :unit)
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @purchases = Purchase.all
  end

  def show
    @purchase = Purchase.find(params[:id])
  end


  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(purchase_params)

    if @purchase.save
      redirect_to @purchase
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @purchase = Purchase.find(params[:id])
  end

  def update
    @purchase = Purchase.find(params[:id])

    if @purchase.update(purchase_params)
      redirect_to new_purchase_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def purchase_params
    params.require(:purchase).permit(:amount, :pricePerUnit, :weightPerUnit, :store, :article_id)
  end

end

app/controllers/recipedetails_controller.rb
class RecipedetailsController < ApplicationController
  def index
    @recipedetails = RecipeDetail.all
  end

  def new
    @recipedetail = RecipeDetail.new
  end

  def create
    @recipedetail = RecipeDetail.new(recipedetails_params)
    if @recipedetail.save
      redirect_back(fallback_location: recipes_path)
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @recipedetail = RecipeDetail.find(params[:id])
  end

  def update
    @recipedetail = RecipeDetail.find(params[:id])
    if @recipedetail.update(recipedetails_params)
    # if @recipedetail.update_attribute(:article_id, params[:article_id])
    # if @recipedetail.update_attribute(:amount, params[:amount])
      #todo: this updates using the value from the DTO, not from the form. Need to take value from the form! change - recipes\edit.view
      redirect_back(fallback_location: recipes_path)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @recipedetails = RecipeDetail.all
  end

  def destroy
    @recipedetail = RecipeDetail.find(params[:id])
    @recipedetail.destroy
    #
    # @recipedetail = RecipeDetail.where("article_id = ? and recipe_id = ?", params[:aid], params[:rid])
    # RecipeDetail.destroy(@recipedetail.id)

    redirect_back(fallback_location: recipes_path)
  end


  private
  def recipedetails_params
    params.permit(:article_id, :recipe_id, :amount)
    # params.delete(:_method)
    # params.delete(:authenticity_token)
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipedetail = RecipeDetail.where("recipe_id = ?", @recipe.id)
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipedetail = RecipeDetail.where("recipe_id = ?", @recipe.id)
  end

  def update
    @recipe = Recipe.find(params[:id])

    @newrecipedetail = RecipeDetail.new(recipedetails_params)

    # if @newrecipedetail.save
    #   redirect_to @recipe
    # else
    #   render :edit, status: :unprocessable_entity
    # end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :output)
  end

  private
  def recipedetails_params
    params.permit(:article_id, :recipe_id, :amount)
  end
end

app/controllers/sale_packages_controller.rb
class SalePackagesController < ApplicationController

  def create
    @sale = Sale.find(params[:sale_id])
    @sale_package = @sale.sale_packages.create(sale_package_params)
    redirect_to sale_path(@sale)
  end

  private
  def sale_package_params
    params.require(:sale_package).permit(:sale_id, :article_id, :amount)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)

    if @sale.save
      redirect_to @sale
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def update
    @sale = Sale.find(params[:id])

    if @sale.update(sale_params)
      calcCost @sale
      redirect_to sales_path
    else
      redirect_to sales_path
    end
  end


  def edit
    @sale = Sale.find(params[:id])
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    redirect_to sales_path, status: :see_other
  end
  def calcCost (sale)
    # @recipe = Recipe.find(sale.recipe_id)
    # sale.update_attribute("clientTmp", @recipe.name)
    cost = 0.0
    RecipeDetail.where(recipe_id: sale.recipe_id).find_each do |rd|
      article = Article.find(rd.article_id)
      latestPurchase = Purchase.where("article_id = ?", rd.article_id).order("created_at DESC").first
      latestCostPerUnit = latestPurchase.pricePerUnit / latestPurchase.weightPerUnit
      amountInRecipe = rd.amount
      tmpCost = latestCostPerUnit * amountInRecipe
      cost = cost + tmpCost
      #todo: calculate packaging cost, implement inventory + its management, implement decoration cost (with checkboxes), implement composite recipes
    end
    sale.update_attribute("clientTmp", sale.clientTmp + cost.to_s + ", ")
    sale.update_attribute("profit", sale.profit+1)
  end

  private
  def sale_params
    params.require(:sale).permit(:recipe_id, :amount, :orderPlaced, :orderDelivery, :clientTmp, :discount, :delivery, :processed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/recipedetails_helper.rb
module RecipedetailsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sale_packages_helper.rb
module SalePackagesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% article.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.select :category, ['Продукт', 'Хозка', 'Пакування'], selected: 'Продукт' %>
  </div>

  <div>
    <%= form.label :unit %><br>
    <%= form.select :unit, ['г', 'мл', 'шт', 'пак'], selected: 'г' %>
  </div>

<!--  <div>-->
<!--    <%#= form.label :category %><br>-->
    <%#= form.text_area :category %>
    <%# article.errors.full_messages_for(:category).each do |message| %>
<!--      <div><%#= message %></div>-->
    <%# end %>
<!--  </div>-->

<!--  <div>-->
<!--    <%#= form.label :unit %><br>-->
    <%#= form.text_area :unit %>
    <%# article.errors.full_messages_for(:unit).each do |message| %>
<!--      <div><%#= message %></div>-->
    <%# end %>
<!--  </div>-->

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
</style>

<table class="tg">
  <thead>
  <tr>
    <th class="tg-0pky">Назва</th>
    <th class="tg-0pky">Категорія</th>
    <th class="tg-0pky">Од. Виміру</th>
    <th class="tg-0pky">Остання ціна в закупці</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
   <tr>
    <td class="tg-0lax">
      <a href="<%= article_path(article) %>">
      <%= article.name %>
      </a>
    </td>
    <td class="tg-0lax"><%= article.category %></td>
    <td class="tg-0lax"><%= article.unit %></td>
<!--    <td class="tg-0lax"><%#= @articles.getLastPrice %></td>-->
  </tr>
  <% end %>
  </tbody>
</table>


<ul>
  <% @articles.each do |article| %>
    <li>
      <a href="<%= article_path(article) %>">
        <%= article.name %>
      </a>
    </li>
  <% end %>

  <%= link_to "New Article", new_article_path %>

  <br>
  <%= link_to "Тех карти", recipes_path %>

  <br>
  <%= link_to "Закупки", purchases_path %>

  <br>
  <%= link_to "Продажі", sales_path %>

<!--  <br>-->
  <%#= link_to "Тех карти detailed", recipedetails_path %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>Name - <%= @article.name %></h1>
<p>Category - <%= @article.category %></p>
<p>Unit - <%= @article.unit %></p>
<p>Last Purchase Price - <%= @lastPrice.pricePerUnit %></p>


<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
  <li>
    <%= button_to 'Destroy', article_path(@article), method: :delete %>
  </li>
</ul>

<br>
<%= link_to "Home", articles_path %>

app/views/purchases/_form.html.erb
<%= form_with model: purchase do |form| %>

  <div>
    <%= form.label :article_id %><br>
    <%= form.collection_select :article_id, Article.order(:name), :id, :name %>
  </div>

  <div>
    <%= form.label :amount %><br>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :store %><br>
    <%= form.select :store, ['Ашан', 'Селгрос', 'Переоблік', 'Allegro'], selected: 'Ашан' %>
  </div>

  <div>
    <%= form.label :pricePerUnit, 'Ціна за од.'%><br>
    <%= form.text_field :pricePerUnit %>
  </div>

  <div>
    <%= form.label :weightPerUnit, 'Вага в од.' %><br>
    <%= form.text_field :weightPerUnit %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/purchases/new.html.erb
<h1>New Purchase Order</h1>

<%= render "form", purchase: @purchase %>

app/views/recipedetails/index.html.erb
<h1>Технологічні Карти</h1>
<br>
<%=link_to "New", new_recipedetail_path %>
<br>


<ul>
  <% @recipedetails.each do |recipe| %>
    <li>
      <%= recipe.article_id %>
    </li>
  <% end %>
</ul>


<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
</style>

<table class="tg">
  <thead>
  <tr>
    <th class="tg-0pky">Назва</th>
    <th class="tg-0pky">Продукт</th>
    <th class="tg-0pky">Од. Виміру</th>
    <th class="tg-0pky">Кількість</th>
  </tr>
  </thead>
  <tbody>
  <% @recipedetails.each do |reciped| %>
    <tr>
      <td class="tg-0lax">
<!--        <a href="<%#= article_path(article) %>">-->
          <%= reciped.recipe.name %>
<!--        </a>-->
      </td>
      <td class="tg-0lax"><%= reciped.article.name %></td>
      <td class="tg-0lax"><%= reciped.article.unit %></td>
      <td class="tg-0lax"><%= reciped.amount %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<ul>
  <% @recipedetails.each do |recipedetail| %>
    <li>
<!--      <a href="<%#= article_path(article) %>">-->
        <%= recipedetail.article.name %>
<!--      </a>-->
    </li>
  <% end %>

</ul>

<!--<p> <%#= @recipedetails.amount %> </p>-->

<br>
<%= link_to "Home", articles_path %>

app/views/recipedetails/new.html.erb
<%#= render "form", recipedetail: @recipedetail %>

<br>
<%= link_to "Home", articles_path %>

app/views/recipedetails/show.html.erb
<br>
<%= link_to "Home", articles_path %>

app/views/recipes/_form.html.erb
<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
</style>

<table class="tg">
  <thead>
  <tr>
    <th class="tg-0pky">Продукт</th>
    <th class="tg-0pky">Од. Виміру</th>
    <th class="tg-0pky">Кількість</th>
    <th class="tg-0pky">Дія</th>
  </tr>
  </thead>
  <tbody>
  <% recipedetail.each do |rd| %>
    <tr>
      <td class="tg-0lax"><%= Article.find(rd.article_id).name %></td>
      <td class="tg-0lax"><%= Article.find(rd.article_id).unit %></td>
      <td class="tg-0lax"><%= rd.amount %></td>
<!--      <td class="tg-0lax"> <%#= button_to 'Видалити', recipedetail_path(rd), method: :delete, params: { aid: rd.article_id, rid: rd.recipe_id  } %> </td>-->
      <td class="tg-0lax"> <%= button_to 'Видалити', recipedetail_path(rd), method: :delete %> </td>
      <%#= button_to 'Destroy', article_path(@article), method: :delete %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
</style>

<h1><%= @recipe.name %></h1>

<%#= render "form", recipedetail: @recipedetail %>

<br>

<%= form_with url: recipedetail_path, method: "patch", model: @recipedetails do |form| %>
<%#= form_with url: recipedetails_path, method: :patch, model: @recipedetails do |form| %>

  <table class="tg">
    <thead>
    <tr>
      <th class="tg-0pky">Продукт</th>
      <th class="tg-0pky">Од. Виміру</th>
      <th class="tg-0pky">Кількість</th>
      <th class="tg-0pky">Дія</th>
    </tr>
    </thead>
    <tbody>
    <% @recipedetail.each do |rd| %>
      <tr>
        <td class="tg-0lax">
          <%= form.collection_select :article_id, Article.order(:name), :id, :name, {:selected => rd.article_id}  %>
        </td>
<!--        <td class="tg-0lax"><%#= Article.find(rd.article_id).name %></td>-->
        <td class="tg-0lax"><%= Article.find(rd.article_id).unit %></td>
        <div hidden>
          <%= form.label :recipe_id %>
          <%#= form.collection_select :recipe_id, Recipe.order(:name), :id, :name, {:selected => @recipe.id}, {:disabled => "true"}  %>
          <%= form.collection_select :recipe_id, Recipe.order(:name), :id, :name, {:selected => @recipe.id}  %>
        </div>

        <td class="tg-0lax"><%= form.text_field :amount, value:rd.amount %></td>
<!--        <td class="tg-0lax"><%#= rd.amount %></td>-->
        <td class="tg-0lax">
          <%#= button_to 'Оновити', recipedetail_path(rd), params: {article_id: rd.article_id, recipe_id: @recipe.id} , method: :patch %>
          <%#= button_to 'Оновити', recipedetail_path(rd), params: {amount: :amount}, method: :patch %>
          <%#= form.submit 'Upd' %>
          <%= button_to 'Видалити', recipedetail_path(rd), method: :delete %>
          <%#= form.submit%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


<%= form_with url: recipedetails_path, model: @recipedetails do |form2| %>
  <div>
    <%= form2.label :amount %><br>
    <%= form2.text_field :amount %>
  </div>

  <div>
    <%= form2.label :article_id %><br>
    <%= form2.collection_select :article_id, Article.order(:name), :id, :name %>
  </div>

  <div hidden>
    <%= form2.label :recipe_id %>
    <%#= form.collection_select :recipe_id, Recipe.order(:name), :id, :name, {:selected => @recipe.id}, {:disabled => "true"}  %>
    <%= form2.collection_select :recipe_id, Recipe.order(:name), :id, :name, {:selected => @recipe.id}  %>
  </div>

  <div>
    <%= form2.submit %>
  </div>
<% end %>

<br>

<br>
<%= link_to "Back", recipes_path %>
<br>
<%= link_to "Home", articles_path %>

app/views/recipes/index.html.erb
<ul>
  <% @recipes.each do |recipe| %>
  <li>
    <%= link_to recipe.name, recipe %>
<!--    <a href = "<%# recipe_path(recipe) %>">-->
     <%#= recipe.name %>
<!--    </a>-->
  </li>
  <% end %>
</ul>


<br>
<%= link_to "New", new_recipe_path %>

<br>
<%= link_to "Home", articles_path %>

app/views/recipes/new.html.erb
<%#= render "form", recipedetail: @recipedetail %>

<br>
<%= link_to "Back", recipes_path %>
<br>
<%= link_to "Home", articles_path %>

app/views/recipes/show.html.erb
<%#= render "form", recipedetail: @recipedetail %>

<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
</style>

<p><%=@recipe.name %></p>

<table class="tg">
  <thead>
  <tr>
    <th class="tg-0pky">Продукт</th>
    <th class="tg-0pky">Од. Виміру</th>
    <th class="tg-0pky">Кількість</th>
  </tr>
  </thead>
  <tbody>
  <% @recipedetail.each do |rd| %>
    <tr>
      <td class="tg-0lax"><%= Article.find(rd.article_id).name %></td>
      <td class="tg-0lax"><%= Article.find(rd.article_id).unit %></td>
      <td class="tg-0lax"><%= rd.amount %></td>
      <!--      <td class="tg-0lax"> <%#= button_to 'Видалити', recipedetail_path(rd), method: :delete, params: { aid: rd.article_id, rid: rd.recipe_id  } %> </td>-->
      <%#= button_to 'Destroy', article_path(@article), method: :delete %>
    </tr>
  <% end %>
  </tbody>
</table>



<br>
<%= link_to "Edit", edit_recipe_path %>
<br>
<%= link_to "Back", recipes_path %>
<br>
<%= link_to "Home", articles_path %>

app/views/sale_packages/_sale_package.html.erb
<li>
    <%= sale_package.amount.to_s + " - " + Article.find(sale_package.article_id).name %>
</li>

app/views/sales/_form.html.erb
<%= form_with model: sale do |form| %>
<%#= form_with model: [sale, sale.sale_packages.build] do |form| %>
  <div>
    <%= form.label :recipe_id %><br>
    <%= form.collection_select :recipe_id, Recipe.order(:name), :id, :name %>
  </div>

  <div>
    <%= form.label :amount %><br>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :orderPlaced %><br>
    <%= form.date_select :orderPlaced %>
  </div>

  <div>
    <%= form.label :orderDelivery %><br>
    <%= form.date_select :orderDelivery %>
  </div>

  <div>
    <%= form.label :clientTmp %><br>
    <%= form.text_field :clientTmp %>
  </div>

  <div>
    <%= form.label :discount %><br>
    <%= form.text_field :discount %>
  </div>

  <div>
    <%= form.label :delivery %><br>
    <%= form.text_field :delivery %>
  </div>

  <div>
    <%= form.label :processed %>
    <%= form.check_box :processed, {:checked => false}  %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

<br>
<%= link_to "Home", articles_path %>

app/views/sales/index.html.erb
<h1>Sales</h1>
<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
</style>

<table class="tg">
  <thead>
  <tr>
    <th class="tg-0pky">ID</th>
    <th class="tg-0pky">Вироб</th>
    <th class="tg-0pky">Дата замовлення</th>
    <th class="tg-0pky">Дата продажу</th>
    <th class="tg-0pky">Клієнт</th>
    <th class="tg-0pky">Кількість</th>
    <th class="tg-0pky">Собівартість</th>
    <th class="tg-0pky">Ціна за од.</th>
    <th class="tg-0pky">Знижка (%)</th>
    <th class="tg-0pky">Доставка</th>
    <th class="tg-0pky">Сума</th>
    <th class="tg-0pky">Прибуток</th>
    <th class="tg-0pky">Оброблено</th>
    <th class="tg-0pky">Дії</th>
  </tr>
  </thead>
  <tbody>
  <% @sales.each do |sale| %>
    <%= form_with model: sale do |form| %>
   <tr>
    <td class="tg-0lax">
      <a href="<%= edit_sale_path(sale) %>">
        <%= sale.id %>
      </a>
    </td>
    <td class="tg-0lax"><%= Recipe.find(sale.recipe_id).name %></td>
    <td class="tg-0lax"><%= sale.orderPlaced %></td>
    <td class="tg-0lax"><%= sale.orderDelivery %></td>
    <td class="tg-0lax"><%= form.text_field :clientTmp, value: sale.clientTmp %></td>
    <td class="tg-0lax"><%= sale.amount %></td>
    <td class="tg-0lax"> cost </td>
    <td class="tg-0lax"> priceperunit </td>
    <td class="tg-0lax"><%= sale.discount %></td>
    <td class="tg-0lax"><%= sale.delivery %></td>
    <td class="tg-0lax">sum</td>
    <td class="tg-0lax"><%= sale.profit %></td>
    <td class="tg-0lax"><%= sale.processed %></td>
<!--    <td class="tg-0lax"><%#= button_to "Some Button", :action=> "calcCost"%></td>-->
    <td class="tg-0lax">
      <%= form.submit %>
    </td>
      <% end %>

     <%#= form_tag add_school_user_path(@user), method: put do -%>
       <%#= hidden_field_tag :school_id, @school.id -%>
       <%#= submit_tag 'Add school' -%>
     <%#- end -%>

  </tr>
  <% end %>
  </tbody>
</table>


  <%= link_to "New Sale", new_sale_path %>

  <br>
  <%= link_to "Тех карти", recipes_path %>

  <br>
  <%= link_to "Закупки", purchases_path %>

<br>
<%= link_to "Home", articles_path %>